---
## You can override the default chart name (i.e., .Charts.name) when desired using the following parameter.
## This is the only way to have more than one deployment of this
nameOverride: null

## Number of Hive Metastore instances.
## Following the documentation, given Hive Metastore is stateless we could have more than one instance.
## https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+Administration
replicaCount: 1

## Default Hive image and tag. Please build image locally before applying this.
image:
#  name: eelsherif/hive-metastore
  name: harbor.dell.com/ai-data/hive-metastore
  tag: latest
  pullPolicy: IfNotPresent

#S3Storage:
#  accounts: []
#    accessKey: "at1-1004811-11ae770e-82ef-432c-b3b5-7c2e6d3750a4"
#    secretkey: "DJcfkwa9pQPtlOvKOzOqOd5J6bTbKF3ieqyqZ7D0"

hiveConfigParameters:
  - key: hive.metastore.event.db.notification.api.auth
    value: "false"
  - key: hadoop.proxyuser.hive.hosts
    value: HS2_HOST
  - key: hadoop.proxyuser.hive.groups
    value: "*"
  - key: datanucleus.autoStartMechanism
    value: SchemaTable

env:
  HIVE_DB_EXTERNAL: "true"
  HIVE_WAREHOUSE_DIR: file:///tmp/
  HIVE_DB_HOST: "10.139.145.3:9432"
  HIVE_DB_NAME: icebergcatalog
  HIVE_DB_USER: icebergcatalogusr
  HIVE_DB_PASS: hg5Mc1NC2pM4


## Resource requests and limits: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi

service:
  type: ClusterIP
  port: 9083

## Auto-scaling (hpa) configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90
