apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.name" . }}-conf-templates
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
data:
  metastore-site.xml: |
    <configuration>
      {{- $metastore_uris :=  regexReplaceAll "(.*)" "thrift://$1:9083" (include "hive-metastore.name" . )  }}
      {{- if index .Values.env "HIVE_METASTORE_URIS"  }}
      {{-   $metastore_uris :=  .Values.env.HIVE_METASTORE_URIS  }}
      {{- end }}
      {{- if eq .Values.env.HIVE_DB_EXTERNAL "true" }}
        <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>jdbc:postgresql://{{ .Values.env.HIVE_DB_HOST }}/{{ .Values.env.HIVE_DB_NAME }}</value>
        </property>
        <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          <value>org.postgresql.Driver</value>
        </property>
        <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>{{ .Values.env.HIVE_DB_USER }}</value>
        </property>
        <property>
          <name> javax.jdo.option.ConnectionPassword</name>
          <value>{{ .Values.env.HIVE_DB_PASS }}</value>
        </property>
      {{- end }}
        <property>
          <name>metastore.expression.proxy</name>
          <value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>
        </property>
        <property>
          <name>metastore.task.threads.always</name>
          <value>org.apache.hadoop.hive.metastore.events.EventCleanerTask,org.apache.hadoop.hive.metastore.MaterializationsCacheCleanerTask</value>
        </property>
        <property>
          <name>datanucleus.autoCreateSchema</name>
          <value>false</value>
        </property>
        <property>
          <name>hive.metastore.uris</name>
          <value>{{ $metastore_uris }}</value>
        </property>
      
      <-- end of S3 configuration -->

        <property>
          <name>hive.metastore.warehouse.dir</name>
          <value>{{ .Values.env.HIVE_WAREHOUSE_DIR }}</value>
        </property>

      {{- range $parameter := .Values.hiveConfigParameters }}
        <property>
          <name>{{ $parameter.key }}</name>
          <value>{{ $parameter.value }}</value>
        </property>
      {{- end }}
    </configuration>
